
name: build

on:
  push:
    branches: [ "main", "tests", "modernize" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: build
      run: swift build -v

    - name: tests
      run: swift test -v

    - name: documentation
      run: |
        swift package \
        --allow-writing-to-directory ./XAttr.doccarchive \
        generate-documentation \
        --output-path ./XAttr.doccarchive \
        --transform-for-static-hosting

    - name: compress documentation
      run: tar -zcvf XAttr.doccarchive.tar.gz XAttr.doccarchive

    - name: publish documentation
      uses: actions/upload-artifact@v3
      with:
        name: XAttr.doccarchive.tar.gz
        path: XAttr.doccarchive.tar.gz
